FarmEasy/Controllers/CropDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FarmEasy.Data;
using FarmEasy.Models;
using FarmEasy.ViewModel.CropDetails;

namespace FarmEasy.Controllers
{
    public class CropDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CropDetailsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CropDetails
        public async Task<IActionResult> Index()
        {
            return View(await _context.CropDetails.ToListAsync());
        }

        // GET: CropDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cropDetails = await _context.CropDetails
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cropDetails == null)
            {
                return NotFound();
            }
            var model = new CreateCropViewModel();
            model.CropDetails = cropDetails;            
            model.SoilTypes= await (from soilType in _context.SoilTypes
                                    join soilTypeMapping in _context.CropSoilMappings on soilType.Id equals soilTypeMapping.SoilId
                                    where soilTypeMapping.CropId==cropDetails.Id
                                    select soilType).ToListAsync();            

            return View(model);
        }

        // GET: CropDetails/Create
        public IActionResult Create()
        {
            var model = new CreateCropViewModel();
            model.SoilTypes = _context.SoilTypes.ToList();
            return View(model);
        }

        // POST: CropDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCropViewModel cropViewModel)
        {
            if (ModelState.IsValid)
            {
                await  _context.CropDetails.AddAsync(cropViewModel.CropDetails);
                await _context.SaveChangesAsync();
                foreach (var sT in cropViewModel.SoilTypeId)
                {
                    await _context.CropSoilMappings.AddAsync(new CropSoilMapping() { CropId = cropViewModel.CropDetails.Id, SoilId = sT });
                    await _context.SaveChangesAsync();
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CropType = await _context.SoilTypes.ToListAsync();
            return View(cropViewModel);
        }

        // GET: CropDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cropDetails = await _context.CropDetails.FindAsync(id);
            if (cropDetails == null)
            {
                return NotFound();
            }
            var model = new CreateCropViewModel();
            model.CropDetails = cropDetails;
            model.SoilTypes = await _context.SoilTypes.ToListAsync();
            model.SoilTypeId = await _context.CropSoilMappings.Where(x => x.CropId == cropDetails.Id).Select(y => y.SoilId).ToArrayAsync();            
            return View(model);
        }

        // POST: CropDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,CreateCropViewModel model)
        {            
            if (id != model.CropDetails.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model.CropDetails);
                    await _context.SaveChangesAsync();
                    var cropSoil = await _context.CropSoilMappings.Where(x => x.CropId == model.CropDetails.Id).ToListAsync();
                    _context.CropSoilMappings.RemoveRange(cropSoil);
                    await _context.SaveChangesAsync();
                    foreach(var sT in model.SoilTypeId)
                    {
                       await _context.CropSoilMappings.AddAsync(new CropSoilMapping() { CropId = model.CropDetails.Id, SoilId = sT });
                       await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CropDetailsExists(model.CropDetails.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: CropDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cropDetails = await _context.CropDetails
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cropDetails == null)
            {
                return NotFound();
            }

            return View(cropDetails);
        }

        // POST: CropDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cropDetails = await _context.CropDetails.FindAsync(id);
            _context.CropDetails.Remove(cropDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CropDetailsExists(int id)
        {
            return _context.CropDetails.Any(e => e.Id == id);
        }
    }
}

FarmEasy/Controllers/PredictionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FarmEasy.Data;
using FarmEasy.Models;
using FarmEasy.ViewModel.Prediction;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Utilities.Helper;

namespace FarmEasy.Controllers
{
    public class PredictionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PredictionController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var model = new PredictionViewModel();
            model.City = await _context.Cities.ToListAsync();
            model.SoilTypes = await _context.SoilTypes.ToListAsync();
            return View(model);
        }
        public async Task<IActionResult> Prediction(PredictionViewModel model)
        {
            if (model.SoilTypeId == 0 || model.CityId == 0)
            {
                return RedirectToAction("Index");
            }
            model.City = await _context.Cities.ToListAsync();
            model.SoilTypes = await _context.SoilTypes.ToListAsync();
            var city = await _context.Cities.Where(x => x.Id == model.CityId).FirstOrDefaultAsync();
            var temprature = await PredictionWeather.Predict(city.CityName);
            var pT = Convert.ToDouble(temprature.ForecastedValue[0]);
            var tempInCel= (pT-32)*5/9;
            var crops = await _context.CropDetails.ToListAsync();
            var predictedCrops = new List<CropDetails>();
            foreach (var crop in crops)
            {
                var St = await _context.CropSoilMappings.Where(x => x.SoilId == model.SoilTypeId && x.CropId == crop.Id).FirstOrDefaultAsync();
                if ((tempInCel >= crop.Temperature_Min && tempInCel <= crop.Temperature_Max) && St != null)
                {
                    predictedCrops.Add(crop);
                }
            }
            model.Crops = predictedCrops;
            return View("Index", model);
        }
    }
}

FarmEasy/Controllers/SoilTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FarmEasy.Data;
using FarmEasy.Models;

namespace FarmEasy.Controllers
{
    public class SoilTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SoilTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SoilTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.SoilTypes.ToListAsync());
        }

        // GET: SoilTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soilType = await _context.SoilTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (soilType == null)
            {
                return NotFound();
            }

            return View(soilType);
        }

        // GET: SoilTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SoilTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SoilName")] SoilType soilType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(soilType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(soilType);
        }

        // GET: SoilTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soilType = await _context.SoilTypes.FindAsync(id);
            if (soilType == null)
            {
                return NotFound();
            }
            return View(soilType);
        }

        // POST: SoilTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SoilName")] SoilType soilType)
        {
            if (id != soilType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(soilType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SoilTypeExists(soilType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(soilType);
        }

        // GET: SoilTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var soilType = await _context.SoilTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (soilType == null)
            {
                return NotFound();
            }

            return View(soilType);
        }

        // POST: SoilTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var soilType = await _context.SoilTypes.FindAsync(id);
            _context.SoilTypes.Remove(soilType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SoilTypeExists(int id)
        {
            return _context.SoilTypes.Any(e => e.Id == id);
        }
    }
}

FarmEasy/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FarmEasy.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FarmEasy.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<UserMaster> _userManager;

        public UsersController(UserManager<UserMaster> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index()
        {
           var users=_userManager.Users.ToList();
            return View(users);
        }
    }
}

FarmEasy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FarmEasy</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="icon" type="imges/jpg" sizes="56x56" href="~/images/logo/fab-icon.jpg">

    <!-- Main style sheet -->
    <link rel="stylesheet" type="text/css" href="~/css/custom.css">
    <!-- responsive style sheet -->
    <link rel="stylesheet" type="text/css" href="~/css/responsive.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">    
    <script src="https://kit.fontawesome.com/644b872e85.js" crossorigin="anonymous"></script>
    <style>

        html,
        body {
            height: 100%;
        }

        .main-container .theme-main-menu .navbar-nav > li > a {
            padding: 30px 0;
        }

        /* Wrapper for page content to push down footer */
        .container {
            min-height: 85%;
            height: auto;
            /* Negative indent footer by it's height */
            margin: 0 auto;            
        }

        #push,
        #footer {
            /*height: 60px;*/
            padding: 0;
        }

        #footer {
            background-color: #f5f5f5;
            margin-top: 100px;
        }

        .main-container .theme-main-menu .logo > a:hover {
            color: #19c40c;
        }

        .main-container .logo {
            margin: 0px;
            padding: 30px 0;
        }

        .social-icon {
            /*display:flex;
        justify-content:center;*/
            align-items: flex-end;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <div class="address-list float_right">
                <partial name="_LoginPartial" />
            </div>
        </div>
        <div class="main-container">
            <div class="container">
                <div class="theme-main-menu">
                    <div class="logo float_left">
                        @*<a asp-controller="Home" asp-action="Index"><img src="~/images/logo/logo.png" alt="logo" class="img-responsive"></a>*@
                        <a asp-controller="Home" asp-action="Index"><img src="~/images/gallary/FarmEasy/LogoMakr_4h05gM.png" alt="logo" class="img-responsive" style="width: 84px; height:45px;"></a>
                    </div> <!-- End of .logo -->

                    <nav class="navbar navbar-default float_right">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse float_left" id="navbar-collapse-1">

                            <ul class="nav navbar-nav">
                                <li class="dropdown-holder">
                                    <a asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="dropdown-holder">
                                    <a asp-controller="Prediction" asp-action="Index">Prediction</a>
                                </li>
                                @*<li class="dropdown-holder">
                                    <a asp-controller="SoilTypes" asp-action="Index">Mandy Price</a>
                                </li>*@
                                <li class="dropdown-holder">
                                    <a asp-controller="CropDetails" asp-action="Index">Crop List</a>
                                </li>
                                <li class="dropdown-holder">
                                    <a asp-controller="SoilTypes" asp-action="Index">Soil Type</a>
                                </li>
                                @if (!User.IsInRole("Admin"))
                                {
                                    <li class="dropdown-holder">
                                        <a asp-controller="ContactUs" asp-action="Create">Contact Us</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="dropdown-holder">
                                        <a asp-controller="ContactUs" asp-action="Index">Contact Us</a>
                                    </li>
                                }
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="dropdown-holder">
                                        <a asp-controller="Users" asp-action="Index">Manage User</a>
                                    </li>
                                }
                            </ul>


                        </div>
                        @*<div class="search_option float_right">
                                <button class="search tran3s dropdown-toggle" id="searchDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-search" aria-hidden="true"></i></button>
                                <form action="#" class="p_color_bg dropdown-menu" aria-labellea:hoverdby="searchDropdown">
                                    <input type="text" placeholder="Search here.....">
                                    <button><i class="fa fa-search" aria-hidden="true"></i></button>
                                </form>
                            </div>  End of .search_option*@
                        <div class="clear_fix"></div>
                    </nav>
                    <div class="clear_fix"></div>
                </div>
            </div>
        </div>
    </header>






    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FarmEasy</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@





    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="col-xt-12">
                <div class="single-list1">
                    <div class="contact-single-list">
                        <div class="contact">
                            <div>
                                <a href="#" class=""><i class="fa fa-phone" aria-hidden="true"></i> ( +91 ) 9727007021</a>
                            </div>
                            <div>
                                <a href="#" class=""><i class="fa fa-envelope-o" aria-hidden="true"></i>farmeasy242573@gmail.com</a>
                            </div>
                        </div>
                        <div>
                            <a href="#" class=""><i class="fa fa-map-marker" aria-hidden="true"></i>123 New Naroda,Ahmedabad</a>
                        </div>
                        <div class="social-icon">
                            <h6>Social touch</h6>
                            @*<ul>*@
                            <a href="#" class=" hvr-shutter-out-horizontal-three"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#" class=" hvr-shutter-out-horizontal-three"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                            <a href="#" class=" hvr-shutter-out-horizontal-three"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#" class="hvr-shutter-out-horizontal-three"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                            @*</ul>*@
                        </div> <!-- /.social-icon -->
                        2020 - FarmEasy - <a asp-area="" asp-controller="Home" asp-action="Index">FarmEasy</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <!-- Js File_________________________________ -->
    <!-- JS offline library -->
    <script src="~/js/jquery.2.2.3.min.js"></script>
    <!-- bootstrap js -->
    <script src="~/resource/bootstrap/js/bootstrap.min.js"></script>
    <!-- Camera js -->
    <script src="~/resource/Camera-master/scripts/camera.min.js"></script>
    <script src="~/resource/Camera-master/scripts/jquery.easing.1.3.js"></script>
    <!-- Owl carousel css-->
    <script src="~/resource/OwlCarousel/dist/owl.carousel.min.js"></script>
    <!-- js count to -->
    <script type="text/javascript" src="~/resource/jquery.appear.js"></script>
    <script type="text/javascript" src="~/resource/jquery.countTo.js"></script>
    <!-- mixitUp -->
    <script type="text/javascript" src="~/resource/jquery.mixitup.min.js"></script>
    <!-- fancy box -->
    <script type="text/javascript" src="~/resource/fancybox/dist/jquery.fancybox.min.js"></script>
    <!-- wow Animation -->
    <script src="~/resource/WOW-master/dist/wow.js"></script>
    <!-- Custom Js -->
    <script src="~/js/custom.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@
    @RenderSection("Scripts", required: false)
</body>
</html>